const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../web');
const artifactDir=path.resolve(__dirname,'../work/music-download-ui-acceptance-20261005');
const playwright=(()=>{try{return require('playwright');}catch{return null;}})();

test('music download and library desktop browser acceptance',{skip:!playwright,timeout:120000},async()=>{
 const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const target=pathname==='/'?path.join(root,'index.html'):pathname.startsWith('/static/')?path.join(root,pathname.slice(8)):null;if(!target||!target.startsWith(root)||!fs.existsSync(target)){res.writeHead(404);return res.end();}const ext=path.extname(target);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.ogg':'audio/ogg'})[ext]||'application/octet-stream');res.end(fs.readFileSync(target));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 fs.mkdirSync(artifactDir,{recursive:true});
 const browser=await playwright.chromium.launch({headless:true,channel:process.env.MALODY_BROWSER_CHANNEL||'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],searchCalls=[],postCalls=[],deleted=new Set();page.on('pageerror',error=>errors.push(error.message));
  const advancedSettings={engine:'mug',strategy:'independent',seed:1,steps:20,ln_ratio:.2,pattern_strength:50,conditions:{mug:{hard:4},v32:{hard:4}},difficulty_rules:{hard:{rate:8.5,peak:15,gap:70,chord:4,hold_ms:4000}}};
  const project={id:'p'.repeat(32),revision:0,title:'已登记高级曲名',artist:'实际音乐人',duration:2,samples:88200,sample_rate:44100,settings:advancedSettings,profile:'keyboard',variants:[{key:'balanced--hard',pattern:'balanced',difficulty:'hard'}],segments:[],assemblies:[],tempo:{bpm:120,points:[[0,120]],uncertain:true},waveform:[.2,.1],tail_trim:{enabled:true,cutoff_sample:88200}};
  const wav=Buffer.alloc(44+88200*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
  let uploaded=false;
  let staleResponse,identifyResponse,holdIdentity=false,downloadCalls=0,failBili=false;
  await page.addInitScript(()=>localStorage.setItem('startrail.appearance.v1',JSON.stringify({theme:'light',trail:false})));
  const yt=(number)=>({id:String(number).padStart(11,'0'),title:'公开音乐 '+number,artist:'音乐人 '+number,channel:'频道 '+number,duration:160,url:'https://www.youtube.com/watch?v='+String(number).padStart(11,'0'),extension:'webm'});
  const records=Array.from({length:15},(_,index)=>({id:'delivery:'+index,job_id:'job'+index,title:'曲包 '+index,artist:'音乐人',engine:index%2?'advanced':'mug',type:index%2?'advanced':'song',status:'completed',download:'/api/library/download?record_id=delivery:'+index,created:'2026-10-05T12:00:00',difficulties:['hard']}));
  await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.method()==='POST'&&!req.headers()['content-type']?.startsWith('multipart/')?req.postDataJSON():null;if(req.method()==='POST')postCalls.push({path:url.pathname,body});let data={};
   if(url.pathname==='/api/advanced/defaults')data={settings:advancedSettings,difficulties:['hard'],capabilities:{music_workflow:1}};
   else if(url.pathname==='/api/advanced/separation/models')data={models:[],defaults:{fast:''}};
   else if(url.pathname==='/api/advanced/projects/upload'){uploaded=true;assert.match(req.postDataBuffer().toString('utf8'),/高级音轨/);data=project;}
   else if(url.pathname==='/api/advanced/projects')data={projects:uploaded?[project]:[]};
   else if(url.pathname.startsWith('/api/advanced/projects/')){if(url.pathname.endsWith('/audio'))return route.fulfill({contentType:'audio/wav',body:wav});else if(url.pathname.endsWith('/tasks'))data={tasks:[]};else if(url.pathname.endsWith('/section-plans'))data={plans:[]};else if(url.pathname.endsWith('/separations'))data={stem_sets:[]};else if(url.pathname.endsWith('/separation-trials'))data={trials:[]};else if(url.pathname.endsWith('/analysis'))return route.fulfill({status:503,json:{detail:'测试不分析音乐'}});else data=project;}
   else if(url.pathname==='/api/music')data=[];
   else if(url.pathname==='/api/health')data={gpu:'test',engines:{mug:{ready:false,label:'MuG'},v32:{ready:false,label:'V32'}}};
   else if(url.pathname==='/api/storage')data={total_bytes:0,outputs_bytes:0,uploads_bytes:0};
   else if(url.pathname==='/api/queue')data={items:[],running:0,waiting:0,paused:0};
   else if(url.pathname==='/api/history'){const current=records.filter(item=>!deleted.has(item.id)),pageNo=Math.min(Number(url.searchParams.get('page')||1),Math.max(1,Math.ceil(current.length/12)));data={items:current.slice((pageNo-1)*12,pageNo*12),page:pageNo,pages:Math.max(1,Math.ceil(current.length/12)),total:current.length,total_all:current.length};}
   else if(url.pathname==='/api/music/search'){const cursor=Number(url.searchParams.get('cursor')),q=url.searchParams.get('q');searchCalls.push({cursor,q,exclude:url.searchParams.get('exclude')||''});if(q==='stale'){await new Promise(resolve=>staleResponse=resolve);}data={results:Array.from({length:q==='short'?3:24},(_,index)=>yt(cursor+index)),next_cursor:cursor+96,scanned:96,has_more:cursor<192};}
   else if(url.pathname==='/api/music-assets/resolve'){if(failBili&&body.input==='bad-bili')return route.fulfill({status:502,json:{detail:'Kipfel 主线路与备用线路解析失败：原始诊断'}});data={candidate:body.input.includes('youtube')?yt(Number(new URL(body.input).searchParams.get('v'))):{id:'bili-BV123-p1',platform:'bilibili',title:'B站歌曲',artist:'原音乐人',duration:100,extension:'m4a',url:'https://www.bilibili.com/video/BV123'}};}
   else if(url.pathname==='/api/music-assets/downloads'&&req.method()==='POST'){downloadCalls++;data={id:'download1',status:'ready',title:body.title,artist:body.artist,source_id:body.source_id,asset:{title:body.title,filename:body.title+' - '+body.artist+'.webm'}};}
   else if(url.pathname==='/api/music-assets/downloads')data={tasks:[]};
   else if(url.pathname==='/api/music-assets')data={assets:[]};
   else if(url.pathname==='/api/music-assets/identify'){if(holdIdentity)await new Promise(resolve=>identifyResponse=resolve);data={asset:{id:'saved',title:'已登记曲名',artist:'实际音乐人',thumbnail:'/static/assets/startrail-mark.svg'}};}
   else if(url.pathname==='/api/library/delete'){data={results:body.record_ids.map(id=>{if(id==='delivery:13')return {record_id:id,deleted:false,error:'文件占用'};deleted.add(id);return {record_id:id,deleted:true};})};}
   return route.fulfill({json:data});
  });
  const origin='http://127.0.0.1:'+server.address().port;await page.goto(origin);
  assert.equal(await page.locator('#studio-view').isVisible(),true);assert.equal(await page.locator('#music-search-form').count(),0);assert.match(await page.locator('#file').getAttribute('accept'),/\.webm,\.aac/);
  await page.locator('#file').setInputFiles({name:'原始音轨.webm',mimeType:'audio/webm',buffer:Buffer.from('registered audio')});await page.waitForFunction(()=>document.querySelector('#title').value==='已登记曲名');assert.equal(await page.locator('#artist').inputValue(),'实际音乐人');assert.equal(postCalls.filter(x=>x.path==='/api/jobs'||x.path.includes('music-analysis')).length,0);
  holdIdentity=true;await page.locator('#file').setInputFiles({name:'迟到识别.aac',mimeType:'audio/aac',buffer:Buffer.from('delayed registered audio')});while(!identifyResponse)await new Promise(resolve=>setTimeout(resolve,10));await page.locator('#title').fill('我确认的曲名');await page.locator('#artist').fill('我确认的音乐人');identifyResponse();await page.waitForFunction(()=>pendingImport===null);assert.equal(await page.locator('#title').inputValue(),'我确认的曲名');assert.equal(await page.locator('#artist').inputValue(),'我确认的音乐人');holdIdentity=false;
  await page.locator('#nav-advanced').click();await page.waitForFunction(()=>document.querySelector('#adv-import-source').options.length===1);assert.match(await page.locator('#adv-file').getAttribute('accept'),/\.webm,\.aac/);await page.locator('#adv-file').setInputFiles({name:'高级音轨.aac',mimeType:'audio/aac',buffer:Buffer.from('registered advanced audio')});await page.waitForFunction(()=>document.querySelector('#aw-song-title').value==='已登记高级曲名');assert.equal(await page.locator('#aw-song-artist').inputValue(),'实际音乐人');assert.equal(postCalls.filter(x=>x.path.endsWith('/music-analysis')||x.path.endsWith('/segmentation-preview')||x.path.endsWith('/confirm-and-generate')).length,0);
  await page.locator('#nav-music').click();await page.locator('#md-query').fill('public music');await page.locator('#md-search').click();await page.locator('#md-results article').nth(23).waitFor();
  const titles=()=>page.locator('#md-results h2').allTextContents();const first=await titles();await page.locator('#md-next').click();await page.waitForFunction(()=>document.querySelector('#md-page').textContent.startsWith('第 2'));const second=await titles();await page.locator('#md-next').click();await page.waitForFunction(()=>document.querySelector('#md-page').textContent.startsWith('第 3'));const third=await titles();assert.equal(new Set([...first,...second,...third]).size,72);assert.deepEqual(searchCalls.map(x=>x.cursor),[0,96,192]);assert.equal(searchCalls[1].exclude.split(',').length,24);assert.equal(searchCalls[2].exclude.split(',').length,48);await page.locator('#md-prev').click();assert.deepEqual(await titles(),second);assert.equal(searchCalls.length,3);
  await page.locator('#md-results button').first().click();await page.locator('#md-confirm-dialog').waitFor({state:'visible'});assert.equal(downloadCalls,0);await page.locator('#md-cancel').click();assert.equal(downloadCalls,0);
  await page.locator('#md-results button').first().click();await page.locator('#md-confirm-dialog').waitFor({state:'visible'});await page.locator('#md-title').fill('中文/日本語:歌曲');await page.locator('#md-artist').fill('实际音乐人');assert.equal(await page.locator('#md-filename').textContent(),'中文_日本語_歌曲 - 实际音乐人.webm');await page.locator('#md-confirm').click();await page.waitForFunction(()=>!document.querySelector('#md-confirm-dialog').open);assert.equal(downloadCalls,1);assert.equal(postCalls.filter(x=>x.path==='/api/jobs').length,0);
  await page.locator('#md-query').fill('short');await page.locator('#md-search').click();await page.waitForFunction(()=>document.querySelectorAll('#md-results article').length===3);assert.match(await page.locator('#md-page').textContent(),/第 1 页/);
  await page.locator('#md-query').fill('stale');await page.locator('#md-search').click();while(!staleResponse)await new Promise(resolve=>setTimeout(resolve,10));await page.locator('#md-query').fill('new query');await page.locator('#md-search-form').evaluate(form=>form.requestSubmit());await page.waitForFunction(()=>document.querySelectorAll('#md-results article').length===24);staleResponse();await page.waitForTimeout(50);assert.match(await page.locator('#md-page').textContent(),/第 1 页/);assert.equal(searchCalls.at(-1).q,'new query');
  await page.locator('#md-tab-bilibili').click();assert.equal(await page.locator('#md-range').isVisible(),false);await page.locator('#md-query').fill('BV123');await page.locator('#md-search').click();await page.waitForFunction(()=>document.querySelector('#md-results h2')?.textContent==='B站歌曲');failBili=true;await page.locator('#md-query').fill('bad-bili');await page.locator('#md-search').click();await page.locator('#md-error').waitFor({state:'visible'});assert.match(await page.locator('#md-error').textContent(),/原始诊断/);assert.equal(await page.locator('#md-retry-search').isVisible(),true);
  await page.locator('#md-tab-youtube').click();await page.locator('#md-query').fill('layout');await page.locator('#md-search').click();await page.locator('#md-results article').nth(23).waitFor();assert.equal(await page.locator('.md-duration').first().isVisible(),true);await page.locator('#md-download-status').evaluate(el=>el.open=false);
  for(const size of [{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}]){await page.setViewportSize(size);for(const theme of ['light','peach','moon','sea','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);const bounds=await page.locator('.md-pagination').boundingBox();assert.ok(bounds.y+bounds.height<=size.height+1,JSON.stringify({theme,size,bounds}));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(artifactDir,`music-${theme}-${size.width}x${size.height}.png`)});await page.locator('#md-results button').first().click();await page.locator('#md-confirm-dialog').waitFor({state:'visible'});const modal=await page.locator('#md-confirm-dialog').boundingBox();assert.ok(modal.x>=0&&modal.y>=0&&modal.x+modal.width<=size.width&&modal.y+modal.height<=size.height);await page.screenshot({path:path.join(artifactDir,`confirm-${theme}-${size.width}x${size.height}.png`)});await page.locator('#md-cancel').click();}}
  await page.locator('#nav-library').click();await page.locator('#history-list article').nth(11).waitFor();await page.locator('#library-select-page').click();assert.match(await page.locator('#library-selected-count').textContent(),/12/);await page.locator('#history-next').click();await page.waitForFunction(()=>document.querySelectorAll('#history-list article').length===3);await page.locator('.library-card-select input').nth(1).check();assert.match(await page.locator('#library-selected-count').textContent(),/13/);await page.locator('#history-sort').selectOption('title');await page.waitForFunction(()=>document.querySelectorAll('#history-list article').length===12);assert.match(await page.locator('#library-selected-count').textContent(),/13/);
  await page.locator('#library-delete-selected').click();assert.equal(await page.locator('#library-delete-list li').count(),13);await page.screenshot({path:path.join(artifactDir,'delete-confirm.png')});await page.locator('#library-delete-confirm').click();await page.waitForFunction(()=>!document.querySelector('#library-delete-dialog').open);assert.match(await page.locator('#library-selected-count').textContent(),/1/);assert.match(await page.locator('#history-error').textContent(),/文件占用/);await page.locator('#history-sort').selectOption('oldest');await page.waitForTimeout(50);assert.match(await page.locator('#history-error').textContent(),/文件占用/);assert.equal(postCalls.filter(x=>x.path==='/api/library/delete').at(-1).body.record_ids.length,13);
  await page.locator('#history-engine').selectOption('advanced');await page.waitForFunction(()=>document.querySelector('#library-selected-count').textContent==='已选 0 个曲包');assert.equal(await page.locator('#library-delete-selected').isDisabled(),true);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(artifactDir,'acceptance.json'),JSON.stringify({date:new Date().toISOString(),kind:'mocked API browser acceptance',actual_download_tested:false,actual_game_tested:false,passed:true,checks:['three cursor pages','cached previous page','underfilled results','stale response protection','cancel without download','explicit confirmed download','Bilibili link-only and diagnostic retry','local file identity without processing','delayed identity preserves user metadata edits','advanced native local file import without processing','deletion failures remain visible through refresh','cross-page ordinary and advanced selection','sort retains selection','filter clears selection','partial deletion failure retains failed choice','15 desktop theme and viewport combinations'],search_calls:searchCalls,download_posts:downloadCalls,delete_calls:postCalls.filter(x=>x.path==='/api/library/delete'),browser_errors:errors},null,2));
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
