"""Build a portable local A/B page from measured, aligned comparison artifacts."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
FOLDER=ROOT/'outputs/separation-evaluation/20261004'
LABELS={'Original':'原曲','Demucs-standard':'Demucs 标准','Demucs-FT':'Demucs FT','Kim-cover-2':'Kim · 2 次覆盖','Kim-cover-4':'Kim · 4 次覆盖'}

def build():
    charts=json.loads((FOLDER/'charts.json').read_text(encoding='utf-8'))
    windows=[]
    for song in ('DNA','MIKU'):
        report=json.loads((FOLDER/song/'comparison.json').read_text(encoding='utf-8'))
        for window in report['windows']:
            row={'title':report['title'],'song':song,'range':window['range_seconds'],'versions':{},'charts':[]}
            for key,data in window['versions'].items():
                row['versions'][key]={'files':{role:Path(file).relative_to(FOLDER).as_posix() for role,file in data['files'].items()},'metrics':data['metrics']}
            row['charts']=[{k:run[k] for k in ('model','role','events','actual_model_seed','evaluation_project_id')}
                          for run in charts['runs'] if run['parent_project_id']==report['project'] and run['range']==row['range'] and run['status']=='completed']
            windows.append(row)
    payload=json.dumps({'windows':windows,'labels':LABELS},ensure_ascii=False).replace('<','\\u003c')
    html=TEMPLATE.replace('__PAYLOAD__',payload)
    target=FOLDER/'listen.html';target.write_text(html,encoding='utf-8')
    return target

TEMPLATE=r'''<!doctype html>
<html lang="zh-Hans"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>分离试听对照 · Startrail</title>
<style>
:root{color-scheme:dark;--bg:#0b181b;--card:#12272c;--ink:#e0eff0;--muted:#97b6bb;--line:#29464c;--a:#72d1c5;--b:#b8a1dc}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 8% 0,#23474088,transparent 45%),radial-gradient(ellipse at 100% 30%,#38345066,transparent 48%),var(--bg);color:var(--ink);font:15px/1.7 system-ui,"Microsoft YaHei",sans-serif}
main{max-width:1180px;margin:auto;padding:38px 24px 50px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:24px;margin-bottom:24px}h1{font-size:32px;letter-spacing:-1px;margin:3px 0 6px}h2{font-size:18px;margin:0 0 12px}h3{font-size:14px;margin:0 0 8px}p{margin:4px 0;color:var(--muted)}.eyebrow{letter-spacing:3px;color:var(--a);font-size:11px}.tag{white-space:nowrap;border:1px solid var(--line);padding:6px 12px;color:var(--a);font-size:13px}.toolbar,.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}.toolbar{grid-template-columns:minmax(0,1fr) 200px;margin-bottom:16px}label{display:grid;gap:6px;font-size:13px;color:var(--muted)}select,button,input{font:inherit}select{width:100%;min-width:0;background:#102226;color:var(--ink);border:1px solid var(--line);padding:10px}button{border:1px solid var(--a);background:#163438;color:var(--ink);cursor:pointer;padding:11px 20px;font-size:15px;font-weight:750;min-height:44px}button:hover,button:focus-visible{outline:1px solid var(--a);outline-offset:3px}.card{min-width:0;border:1px solid var(--line);border-top:3px solid var(--a);padding:18px;background:var(--card)}.card.b{border-top-color:var(--b)}.card.b button{border-color:var(--b);background:#2b2a3f}.card button{width:100%;margin-top:14px}.card button[aria-pressed=true]{color:var(--a);box-shadow:inset 0 -2px var(--a)}.card.b button[aria-pressed=true]{color:var(--b);box-shadow:inset 0 -2px var(--b)}.deck{margin:16px 0 24px;border:1px solid var(--line);background:#102428;padding:18px}.deck-top{display:flex;gap:16px;align-items:center;justify-content:space-between;margin-bottom:8px}.deck-top strong{font-size:14px;color:var(--a)}.deck-options{display:flex;gap:16px;flex-wrap:wrap}.deck-options label{display:flex;align-items:center;gap:6px}input[type=checkbox]{accent-color:var(--a);width:16px;height:16px}audio{display:block;width:100%;height:40px}.clock{font-variant-numeric:tabular-nums;color:var(--muted);font-size:13px;margin-top:6px}#status{color:#e7cb8d;font-size:13px;min-height:20px}.evidence{background:#122529aa;border:1px solid var(--line);padding:18px;margin-top:16px}.charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.chart{border:1px solid var(--line);padding:12px;background:#0c1d21}.chart svg{width:100%;display:block;height:100px}.chart small{color:var(--muted);font-size:12px}table{width:100%;border-collapse:collapse;font-size:13px;font-variant-numeric:tabular-nums}th,td{text-align:right;padding:9px 7px;border-bottom:1px solid var(--line)}th:first-child,td:first-child{text-align:left}th{font-weight:500;color:var(--muted)}.note{font-size:13px;margin-top:14px}.foot{margin-top:26px;font-size:12px;color:var(--muted)}.metrics{overflow:auto}[hidden]{display:none!important}
@media(max-width:700px){main{padding:22px 14px}header{display:block}h1{font-size:27px}.tag{display:inline-block;margin-top:10px}.toolbar,.pair,.charts{grid-template-columns:1fr}.deck-top{flex-wrap:wrap}.evidence{padding:13px}th,td{padding:7px 4px;font-size:12px}}
</style>
<main><header><div><div class="eyebrow">STARTRAIL / SEPARATION LAB</div><h1>分离试听对照</h1><p>两首歌曲 · 六个重点片段 · 同一秒切换版本，听清声音和采音的差别。</p></div><div class="tag">本地文件 · 原曲时钟</div></header>
<div class="toolbar"><label>音乐片段<select id="window" aria-label="音乐片段"></select></label><label>对比声部<select id="role" aria-label="对比声部"><option value="accompaniment">伴奏</option><option value="vocals">人声</option></select></label></div>
<div class="pair"><section class="card"><h2>A · 对照版本</h2><select id="a" aria-label="A 对照版本"></select><button id="play-a">播放 A</button></section><section class="card b"><h2>B · 对照版本</h2><select id="b" aria-label="B 对照版本"></select><button id="play-b">播放 B</button></section></div>
<section class="deck"><div class="deck-top"><strong id="source">选择 A 或 B 开始试听</strong><div class="deck-options"><label><input id="loop" type="checkbox" checked>循环片段</label><label><input id="match" type="checkbox" checked>音量匹配</label></div></div><audio id="audio" controls preload="metadata"></audio><div class="clock" id="clock"></div><div id="status" role="status"></div></section>
<section class="evidence" id="chart-panel" hidden><h2>同窗口的 V32 采音对照</h2><p id="chart-protocol" class="note"></p><div id="charts" class="charts"></div><p class="note">四行分别对应四轨，短标为音符头，长线为长条。播放指示线与原曲共用时间；可以核对 16 秒附近和高速连唱段的落键。</p></section>
<section class="evidence"><h2>声音变化记录</h2><div class="metrics"><table><thead><tr><th>版本</th><th>人声 RMS</th><th>伴奏 RMS</th><th>伴奏低频占比</th></tr></thead><tbody id="metrics"></tbody></table></div><p class="note">这些数值描述能量分布。结合原曲比较串音、人声完整度、和声、鼓点和金属感；实际采音质量需要听音与试玩判断。</p></section>
<p class="foot">试听文件从同一份原曲 PCM 按整数采样裁剪，并使用共同防削波增益。可选音量匹配只降低较响一路。所有原始音频、旧版本和谱面保持原样。完整数据见本目录的 comparison.json、hardware.json 和 charts.json。</p></main>
<script>
const DATA=__PAYLOAD__, $=id=>document.getElementById(id), audio=$('audio'), colors=['#62cadc','#85aff0','#ebc263','#e586b8'];let active=null,seq=0,loadedFile=null,objectURL=null;
DATA.windows.forEach((w,i)=>{const o=new Option((w.song==='DNA'?'D/N/A':'初音未来的消失')+' · '+w.range[0]+'–'+w.range[1]+' 秒',i);$('window').add(o)});
for(const id of ['a','b'])for(const key of Object.keys(DATA.labels))$(id).add(new Option(DATA.labels[key],key));$('a').value='Demucs-standard';$('b').value='Kim-cover-4';
function current(){return DATA.windows[Number($('window').value)]}function info(key){const w=current(),v=w.versions[key],role=key==='Original'?'original':$('role').value;return {file:v.files[role],rms:v.metrics[role].rms,label:DATA.labels[key]+' / '+(role==='original'?'原曲':role==='vocals'?'人声':'伴奏')}}
function gain(slot){const a=info($('a').value),b=info($('b').value),x=slot==='a'?a:b;if(!$('match').checked||Math.min(a.rms,b.rms)<1e-7)return 1;return Math.min(a.rms,b.rms)/x.rms}
async function play(slot, resume=true){const n=++seq,w=current(),x=info($(slot).value),t=Math.min(audio.currentTime||0,w.range[1]-w.range[0]-.01);audio.pause();$('status').textContent='';audio.volume=gain(slot);if(loadedFile!==x.file){let url=x.file;try{if(location.protocol!=='file:'){const response=await fetch(x.file);if(!response.ok)throw new Error('试听文件读取失败');const blob=await response.blob();if(n!==seq)return;if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(blob);url=objectURL;}if(n!==seq)return;audio.src=url;loadedFile=x.file;await new Promise((resolve,reject)=>{if(audio.readyState>=3)return resolve();const timer=setTimeout(()=>finish(false),12000);const done=()=>finish(true),failed=()=>finish(false);function finish(ok){clearTimeout(timer);audio.removeEventListener('canplay',done);audio.removeEventListener('error',failed);ok?resolve():reject(new Error('试听文件加载失败，请保持 listen.html 与音频文件夹在一起。'))}audio.addEventListener('canplay',done);audio.addEventListener('error',failed)});}catch(e){loadedFile=null;$('status').textContent=e.message;return}}if(n!==seq)return;audio.currentTime=Math.max(0,t);audio.loop=$('loop').checked;active=slot;$('source').textContent=slot.toUpperCase()+' · '+x.label;for(const s of ['a','b'])$('play-'+s).setAttribute('aria-pressed',String(s===slot));try{if(resume)await audio.play()}catch{$('status').textContent='点击音频播放按钮继续。'}}
function chart(key){const role=key==='Original'?'original':$('role').value;return current().charts.find(r=>r.model===key&&r.role===role)}
function render(){seq++;audio.pause();audio.removeAttribute('src');audio.load();if(objectURL)URL.revokeObjectURL(objectURL);objectURL=loadedFile=null;active=null;$('source').textContent=current().title;for(const s of ['a','b'])$('play-'+s).setAttribute('aria-pressed','false');const rows=$('metrics');rows.replaceChildren();for(const [key,v]of Object.entries(current().versions)){if(key==='Original')continue;const tr=document.createElement('tr');for(const text of [DATA.labels[key],v.metrics.vocals.rms.toFixed(4),v.metrics.accompaniment.rms.toFixed(4),(100*v.metrics.accompaniment.bands['20-200'].fraction).toFixed(1)+'%']){const td=document.createElement('td');td.textContent=text;tr.append(td)}rows.append(tr)}renderCharts();tick()}
function renderCharts(){const w=current(),panel=$('chart-panel'),host=$('charts');host.replaceChildren();panel.hidden=!w.charts.length;if(panel.hidden)return;$('chart-protocol').textContent='Hard · '+(w.song==='DNA'?'Balanced':'Speed')+' · 实际种子 '+w.charts[0].actual_model_seed+' · 原谱保留，关闭动态增强与密度分层';for(const key of new Set(['Original',$('a').value,$('b').value])){const row=chart(key);if(!row)continue;const lo=w.range[0]*1000,span=(w.range[1]-w.range[0])*1000;let marks='';for(let lane=0;lane<4;lane++)marks+='<line x1="0" y1="'+(lane*20+12)+'" x2="600" y2="'+(lane*20+12)+'" stroke="#29464c"/>';for(const e of row.events){const x=(e.start_ms-lo)/span*600,y=e.lane*20+8,width=e.end_ms==null?2.2:Math.max(2.2,(Math.min(e.end_ms,w.range[1]*1000)-e.start_ms)/span*600);marks+='<rect x="'+x+'" y="'+y+'" width="'+width+'" height="7" rx="1" fill="'+colors[e.lane]+'"/>'}const box=document.createElement('article');box.className='chart';const title=document.createElement('h3');title.textContent=DATA.labels[key]+' · '+row.events.length+' 音符';box.append(title);const plot=document.createElementNS('http://www.w3.org/2000/svg','svg');plot.setAttribute('viewBox','0 0 600 88');plot.setAttribute('aria-label',title.textContent+'时间对照');plot.innerHTML=marks+'<line class="playhead" x1="0" x2="0" y1="0" y2="84" stroke="#e0eff0" opacity=".8"/>';box.append(plot);host.append(box)}}
function tick(){const w=current(),local=audio.currentTime||0;$('clock').textContent='原曲 '+(w.range[0]+local).toFixed(3)+' 秒 / '+w.range[1].toFixed(3)+' 秒';for(const line of document.querySelectorAll('.playhead')){const x=local/(w.range[1]-w.range[0])*600;line.setAttribute('x1',x);line.setAttribute('x2',x)}}
for(const slot of ['a','b']){$('play-'+slot).onclick=()=>play(slot);$(slot).onchange=()=>{const resume=!audio.paused;audio.pause();renderCharts();if(active)play(active,resume)}}$('window').onchange=render;$('role').onchange=()=>{const resume=!audio.paused;audio.pause();renderCharts();if(active)play(active,resume)};$('loop').onchange=()=>audio.loop=$('loop').checked;$('match').onchange=()=>{if(active)audio.volume=gain(active)};audio.addEventListener('timeupdate',tick);audio.addEventListener('error',()=>{$('status').textContent='找不到试听音频，请保持整个对照文件夹在一起。'});render();
</script></html>'''

if __name__=='__main__':print(build())
